### ISSUE TITLE
Tabletop Simulator: Music

### ISSUE THREAD

**Issue by elliottomlinson** [elliottomlinson/cardmaster#118]
We've solved this for now by using synctube but that has its own set of limitations. It'd be nice not to have to leave Tabletop Simulator to work the music.

**Comment by DuncanUszkay1** [comment]
>I'll take another look at this at some point in the next few weeks.

Let's not add this kind of thing in issues. We should only claim work when:
- We're working on it right now
- Nobody else can work on it

When neither of those is true, it's just restrictive. We should just make issues, make it clear what's required to complete them, then whoever has time next can complete the issue.

We also shouldn't stick a timeline on it. It's best to keep timeline management at a higher level where we're looking at all the issues at once and can prioritize appropriately. For this project, we don't have any timelines so really we should just omit them altogether.
