### ISSUE TITLE
Rules Card

### ISSUE THREAD

**Issue by elliottomlinson** [elliottomlinson/cardmaster#93]
## Rules Card: Definitions

The *Rules Card* might be a good place include definitions of terms we use. From a cursory look over the cards we use very few 'gaming' terms and could define\clarify them here too. ex.

### Cardmaster Terms
 Term | Definition
-- | --
Action | Your turn in combat, anything your character attempts to do without using a ⚡
"A roll" | Any present or future roll of a dice
... | etc

To consider once we're able to produce cards from a template and asses how they look: we could also use them to shorten ⚡/ ✋ rules with common terms, ex.
 
 ### Rules-Text Abbreviations
 Term | Definition
-- | --
NPC | Non-Player Character
HP | Hit Points
DMG | Damage
d6 | 6-Sided Die
... | etc

or glyphs, unsure about this though I do like the way it looks

 ### Rules-Text Glyphs
 Term | Definition
-- | --
🧍  | Non-player character
❤️  | Health
💔  | Damage
🎲 | 6-Sided Die
... | etc

_Originally posted by @elliottomlinson in https://github.com/elliottomlinson/rpcg/issues/91#issuecomment-891250889_

**Comment by elliottomlinson** [comment]
We should be sure to include *Advantage* and *Disadvantage*

**Comment by DuncanUszkay1** [comment]
Going to take a crack at the content:

## Cardmaster Terms
**Card**
Cards represent magical powers that can be used by characters.

**Hand**
The cards held by a character. At the start of a game, characters can put up to 15 cards that they own into their hand. Characters gain the card's hand effect while holding the card, if applicable. The hand effect of a card is marked by the ✋ symbol.

**Casting**
At any time, a character may move a **Card** out of their **Hand** to instantly activate that Card's Cast Effect.
The cast effect of a card is marked by the :zap: symbol. 

**Colors**
Each Card has an associated colour. Cards are organized into 

**Upgrade**

Cards can be upgraded

**Comment by DuncanUszkay1** [comment]
Going to crack out the ol english style guide on these in a bit 👀

**Comment by DuncanUszkay1** [comment]
I think we should make the two cards separate, in case you're using cardmaster cards in a different game like DnD.

**Comment by DuncanUszkay1** [comment]
>We should also define Unarmed, Melee, and Ranged along with associated damage values

We no longer mention unarmed directly in the rules. I think that the damage values and the concept of being unarmed should just be suggestions to the DM.
